version: "3"
services:
  planning-poker-be:
    container_name: planning-poker-be
    restart: on-failure
    build:
      context: .
      args:
        - NODE_ENV=dev
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - pp-mongodb
    
  pp-mongodb:
    container_name: pp-mongodb
    image: public.ecr.aws/bitnami/mongodb:latest
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGODB_ROOT_PASSWORD: "password123"
      MONGODB_USERNAME: "myuser"
      MONGODB_PASSWORD: "password123"
      MONGODB_DATABASE: "planning_poker"
    volumes:
      - mongodb-pp:/bitnami/mongodb
volumes:
  mongodb-pp:
